
'use strict';
const $=id=>document.getElementById(id),canvas=$('world');
const words={en:{title:'Skyball Sprint',round:'ROUND',rank:'PLACE',time:'TIME',energy:'Ball size',keyboard:'Arrows to move · Camera follows the red runner',touch:'Move with stick · Tap ground to walk',build:'Build stairs ↑',cost:'4 steps per full ball',collect:'Roll on the floor',grow:'Grow your ball',climb:'Race to the top',restart:'Restart round',intro:'You are the red runner. Move on the floor to grow your ball.<br>Enter any lane to build. Only you can help other runners!',start:'Start racing',loading:'Preparing the arena…',stairs:'Stairs',you:'YOU',need:'Move on the floor to grow your ball first',full:'Ball is full! Roll to the red stair entrance',building:'Climbing. Move back manually when the ball runs out',back:'Ball used up. Move back down the stairs manually',win:'First to the finish!',lose:'So close!',next:'Next round',retry:'Race again',paused:'Race paused',resume:'Resume race',pauseInfo:'Take a breath. The finish is waiting.',complete:'All three rounds won!',again:'Play again',best:'Round best',result:'Time',ready:'GO!',tip:'Move to grow the ball. Roll to the red entrance to climb',rivals:['YOU','Violet','Mint','Amber']}};
let lang='en',state='loading',round=1,elapsed=0,count=3,players=[],crystals=[],effects=[],keys={},target=null,joystick={x:0,y:0},view={w:0,h:0,s:1,x:0,y:0},last=0,toastTime=0,best={},images={},startMode='start';
try{best=JSON.parse(localStorage.getItem('skyball-best-3d-v1')||'{}')}catch(e){}
const T=k=>words[lang][k],clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=(a,b)=>a+Math.random()*(b-a),distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),stepsNeeded=()=>18+(round-1)*4;
function applyLanguage(){document.documentElement.lang='en';document.querySelectorAll('[data-i]').forEach(e=>e.textContent=T(e.dataset.i));$('pause').ariaLabel='Pause / resume';if(state==='ready'||state==='loading')showIntro();if(state==='paused')showPause();if(state==='finished')showResult();hud()}
function toast(message){$('notice').textContent=message;toastTime=3;$('notice').style.opacity=1}
function reset(){elapsed=0;target=null;keys={};joystick={x:0,y:0};effects=[];crystals=[];players=[-4.5,-1.5,1.5,4.5].map((lane,i)=>({x:lane,y:3,lane,energy:0,floorDistance:0,roll:0,dirX:-.7,dirY:-.7,built:0,mode:'gather',phase:rand(0,6),speed:i===0?4.6:2.15+i*.18+(round-1)*.2,id:i,activeLane:i,goal:null,wait:0,finished:false}));view.x=0;view.y=0;rebuildCourse();hud()}
function showIntro(){startMode='start';$('cardTitle').textContent=T('title');$('description').innerHTML=T('intro');$('start').textContent=T(state==='loading'?'loading':'start');$('start').disabled=state==='loading';$('steps').classList.remove('hidden');$('restart').classList.add('hidden');$('rankList').innerHTML='';$('eyebrow').textContent='A RACE ABOVE THE CLOUDS';$('record').textContent=best[round]?`${T('best')} · ${best[round].toFixed(1)}s`:'';}
function startRace(){reset();state='playing';$('start').disabled=false;count=0;$('overlay').classList.add('hidden');$('countdown').textContent='';toastTime=0;$('notice').style.opacity=0;}
function laneOwner(p){return players[p.id===0?p.activeLane:p.id]}
function entryOwner(p){return p.id===0?players.reduce((a,b)=>Math.abs(p.x-a.lane)<Math.abs(p.x-b.lane)?a:b):p}
function requestBuild(p){if(p.mode!=='gather')return;const owner=entryOwner(p);if(Math.abs(p.x-owner.lane)>=.8||p.y>=.55)return;if(p.energy<9){if(p.id===0)toast(T('need'));return}p.activeLane=owner.id;p.mode='approach';p.goal={x:owner.lane,y:.15};if(p.id===0){target=null;toast(owner.id===0?T('building'):`Building lane ${owner.id+1} with your ball`)}}
function moveTo(p,dest,speed,dt){const d=distance(p,dest);if(d<speed*dt){p.x=dest.x;p.y=dest.y;return true}p.x+=(dest.x-p.x)/d*speed*dt;p.y+=(dest.y-p.y)/d*speed*dt;p.phase+=dt*12;return false}
function updatePlayer(p,dt){
const owner=laneOwner(p);const oldX=p.x,oldY=p.y,oldMode=p.mode;p.wait=Math.max(0,p.wait-dt);
if(p.mode==='approach'){if(moveTo(p,{x:owner.lane,y:.15},p.speed,dt))p.mode='build'}
else if(p.mode==='build'){const frontier=-(owner.built*.65+.25);if(moveTo(p,{x:owner.lane,y:frontier},p.speed,dt)&&p.wait===0){if(owner.built>=stepsNeeded()){p.finished=true;finish(p.id);return}if(p.energy>=9){p.energy-=9;owner.built++;p.wait=0;effects.push({x:p.x,y:p.y,z:owner.built*.18,life:.6,text:'+1',color:'#fff'})}else{p.mode=p.id===0?'stairs':'return';if(p.id===0){target=null;toast(T('back'))}}}}
else if(p.mode==='stairs'){
let dx=(keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0)+joystick.x,dy=(keys.ArrowDown||keys.s?1:0)-(keys.ArrowUp||keys.w?1:0)+joystick.y;
const mag=Math.hypot(dx,dy),along=-dx*Math.sin(cameraYaw)+dy*Math.cos(cameraYaw);
if(mag>.08){target=null;if(Math.abs(along)>.08){const old=p.y;p.y=clamp(p.y+Math.sign(along)*Math.min(1,mag)*p.speed*dt,-(owner.built*.65+.25),1.3);if(p.y!==old)p.phase+=dt*12}}
else if(target){moveTo(p,{x:owner.lane,y:1.3},p.speed,dt)}
p.x=owner.lane;if(p.y>=.1){p.mode='gather';target=null;p.goal=null}
}
else if(p.mode==='return'){if(moveTo(p,{x:owner.lane,y:1.3},p.speed,dt)){p.mode='gather';p.goal=null}}
else if(p.id===0){let dx=(keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0)+joystick.x,dy=(keys.ArrowDown||keys.s?1:0)-(keys.ArrowUp||keys.w?1:0)+joystick.y;const m=Math.hypot(dx,dy);if(m>.08){target=null;dx/=Math.max(1,m);dy/=Math.max(1,m);const wx=dx*Math.cos(cameraYaw)+dy*Math.sin(cameraYaw),wy=-dx*Math.sin(cameraYaw)+dy*Math.cos(cameraYaw);p.x=clamp(p.x+wx*p.speed*dt,-5.7,5.7);p.y=clamp(p.y+wy*p.speed*dt,.1,6.9);p.phase+=dt*12}else if(target){if(moveTo(p,target,p.speed,dt))target=null}}
else{if(p.energy>=Math.min(36,(stepsNeeded()-owner.built)*9)){p.goal={x:owner.lane,y:.15}}else if(!p.goal||distance(p,p.goal)<.2){p.goal={x:rand(-5.4,5.4),y:rand(2,6.5)}}if(p.goal)moveTo(p,p.goal,p.speed,dt)}
const traveled=Math.hypot(p.x-oldX,p.y-oldY);if(traveled>.0001){p.dirX=(p.x-oldX)/traveled;p.dirY=(p.y-oldY)/traveled;p.roll+=traveled*1.5}
if(oldMode==='gather'&&p.mode==='gather'){const was=p.energy;p.floorDistance+=traveled;const growthDistance=Math.max(0,p.floorDistance-1.4)-Math.max(0,p.floorDistance-traveled-1.4);p.energy=Math.min(36,p.energy+growthDistance*3.5);if(p.id===0&&was<36&&p.energy>=36)toast(T('full'));if(p.energy>=9&&Math.abs(p.x-entryOwner(p).lane)<.8&&p.y<.55){requestBuild(p)}}
}
function finish(id){if(state!=='playing')return;state='finished';players.winner=id;if(id===0){best[round]=Math.min(best[round]||Infinity,elapsed);try{localStorage.setItem('skyball-best-3d-v1',JSON.stringify(best))}catch(e){}}showResult();$('overlay').classList.remove('hidden');}
function showResult(){$('start').disabled=false;const won=players.winner===0;startMode=won?'next':'retry';$('eyebrow').textContent=won?'FINISH LINE / WINNER':'FINISH LINE / TRY AGAIN';$('cardTitle').textContent=T(won?(round===3?'complete':'win'):'lose');$('description').textContent=`${T('result')} ${elapsed.toFixed(1)}s · ${T('stairs')} ${players[0].built} / ${stepsNeeded()}`;$('steps').classList.add('hidden');$('rankList').textContent=players.slice().sort((a,b)=>(b.finished-a.finished)||(b.built-a.built)).map((p,i)=>`${i+1}. ${T('rivals')[p.id]}`).join('　');$('start').textContent=T(won?(round===3?'again':'next'):'retry');$('restart').classList.add('hidden');$('record').textContent=best[round]?`${T('best')} · ${best[round].toFixed(1)}s`:'';}
function showPause(){$('start').disabled=false;startMode='resume';$('cardTitle').textContent=T('paused');$('description').textContent=T('pauseInfo');$('eyebrow').textContent='TAKE YOUR TIME';$('steps').classList.add('hidden');$('rankList').textContent='';$('start').textContent=T('resume');$('restart').classList.remove('hidden');$('record').textContent='';}
function togglePause(){if(state==='playing'){state='paused';keys={};joystick={x:0,y:0};showPause();$('overlay').classList.remove('hidden')}else if(state==='paused'){state='playing';$('overlay').classList.add('hidden')}}
function hud(){if(!players.length)return;const p=players[0];$('level').textContent=String(round).padStart(2,'0');$('energy').textContent=`${Math.floor(p.energy)} / 36`;$('energyBar').style.width=`${p.energy/36*100}%`;$('progress').textContent=`${T('stairs')} ${laneOwner(p).built} / ${stepsNeeded()} · ${p.activeLane+1} lane`;$('timer').textContent=`${String(Math.floor(elapsed/60)).padStart(2,'0')}:${String(Math.floor(elapsed%60)).padStart(2,'0')}`;$('rank').textContent=`${1+players.slice(1).filter(o=>o.built>p.built||(o.built===p.built&&o.energy>p.energy)).length} / 4`;}
let renderer,scene,camera,course,runnerModels=[],stairModels=[],sun;
const cameraYaw=.5,cameraDistance=7;let cameraFocus=new THREE.Vector3(0,0,1),lastRenderTime=0;
const colors=[0xf02d48,0x9d46e6,0x24cb73,0xf79a24],raycaster=new THREE.Raycaster(),floorPlane=new THREE.Plane(new THREE.Vector3(0,1,0),0);
function metalTexture(){const c=document.createElement('canvas');c.width=c.height=256;const g=c.getContext('2d');g.fillStyle='#39434e';g.fillRect(0,0,256,256);for(let y=16;y<256;y+=32)for(let x=16;x<256;x+=32){g.fillStyle='#65717b';g.beginPath();g.arc(x,y+1,9,0,Math.PI*2);g.fill();const grd=g.createRadialGradient(x-2,y-3,1,x,y,8);grd.addColorStop(0,'#070c13');grd.addColorStop(.7,'#101923');grd.addColorStop(1,'#4c5863');g.fillStyle=grd;g.beginPath();g.arc(x,y,8,0,Math.PI*2);g.fill()}const texture=new THREE.CanvasTexture(c);texture.wrapS=texture.wrapT=THREE.RepeatWrapping;texture.colorSpace=THREE.SRGBColorSpace;return texture}
const metalMap=metalTexture();
function metal(repeatX,repeatY){const tex=metalMap.clone();tex.repeat.set(repeatX,repeatY);tex.needsUpdate=true;return new THREE.MeshStandardMaterial({color:0xbcc6cf,map:tex,bumpMap:tex,bumpScale:.055,metalness:.65,roughness:.32})}
const trim=new THREE.MeshStandardMaterial({color:0xeaf1f3,metalness:.35,roughness:.26}),dark=metal(1,1),sphereGeo=new THREE.SphereGeometry(1,32,24);
function box(w,h,d,mat,x,y,z,parent=course){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh}
function bar(a,b,r,material,parent=course){const dir=new THREE.Vector3().subVectors(b,a),m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,dir.length(),10),material);m.position.copy(a).add(b).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),dir.normalize());m.castShadow=true;parent.add(m);return m}
function runner(color){const group=new THREE.Group(),body=new THREE.Group();group.add(body);const mat=new THREE.MeshPhysicalMaterial({color,roughness:.23,metalness:.08,clearcoat:1});const part=(geo,x,y,z)=>{const m=new THREE.Mesh(geo,mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;body.add(m);return m};part(new THREE.SphereGeometry(.28,28,20),0,1.38,0);part(new THREE.CapsuleGeometry(.18,.39,6,14),0,.9,0);const limbs=[];for(const sign of [-1,1]){const leg=new THREE.Group();leg.position.set(sign*.12,.68,0);body.add(leg);const l=new THREE.Mesh(new THREE.CapsuleGeometry(.075,.38,5,10),mat);l.position.y=-.23;l.castShadow=true;leg.add(l);const foot=new THREE.Mesh(new THREE.CapsuleGeometry(.08,.13,4,10),mat);foot.rotation.x=Math.PI/2;foot.position.set(0,-.49,.055);foot.castShadow=true;leg.add(foot);limbs.push(leg);const shoulder=new THREE.Vector3(sign*.22,1.1,.01),elbow=new THREE.Vector3(sign*.29,.91,.28),hand=new THREE.Vector3(sign*.2,.96,.48);bar(shoulder,elbow,.065,mat,body);bar(elbow,hand,.06,mat,body);part(new THREE.SphereGeometry(.075,12,10),hand.x,hand.y,hand.z)}scene.add(group);const ball=new THREE.Mesh(sphereGeo,metal(4,2));ball.castShadow=true;ball.receiveShadow=true;scene.add(ball);return{group,body,limbs,ball,last:new THREE.Vector3()}}
function rebuildCourse(){if(!scene)return;if(course){scene.remove(course);course.traverse(o=>{if(o.geometry)o.geometry.dispose()})}course=new THREE.Group();scene.add(course);stairModels=[];box(13,.5,8,trim,0,-.28,3.5);box(12.9,.055,7.9,metal(9,6),0,-.003,3.5);for(let i=0;i<4;i++){const lane=players[i].lane,mark=new THREE.MeshStandardMaterial({color:colors[i],roughness:.4});box(1.8,.035,.17,mark,lane,.04,.15);const steps=[];for(let n=1;n<=stepsNeeded();n++){const y=n*.18,z=-n*.65;const m=box(1.78,.18,.66,dark,lane,y-.09,z);m.visible=false;steps.push(m);if(n%4===0||n===1||n===stepsNeeded()){for(const side of [-1,1]){bar(new THREE.Vector3(lane+side*.95,y,z),new THREE.Vector3(lane+side*.95,y+.85,z),.045,trim);const cap=new THREE.Mesh(new THREE.SphereGeometry(.085,12,8),trim);cap.position.set(lane+side*.95,y+.87,z);course.add(cap)}}}for(const side of [-1,1]){const a=new THREE.Vector3(lane+side*.89,0,0),b=new THREE.Vector3(lane+side*.89,stepsNeeded()*.18,-stepsNeeded()*.65),direction=new THREE.Vector3().subVectors(b,a);const edge=new THREE.Mesh(new THREE.BoxGeometry(.065,direction.length(),.065),trim);edge.position.copy(a).add(b).multiplyScalar(.5);edge.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),direction.normalize());edge.castShadow=true;course.add(edge)}for(const side of [-1,1])bar(new THREE.Vector3(lane+side*.95,.93,-.4),new THREE.Vector3(lane+side*.95,stepsNeeded()*.18+.85,-stepsNeeded()*.65),.035,trim);stairModels.push(steps)}const fy=-stepsNeeded()*.65-1.3,h=stepsNeeded()*.18;box(13,.5,3.2,trim,0,h-.28,fy);box(12.9,.05,3.1,metal(9,2),0,h,fy);for(let x=-6;x<=6;x++)for(let z=0;z<2;z++)box(.48,.022,.35,new THREE.MeshStandardMaterial({color:(x+z)%2===0?0xffffff:0x101820}),x*.94,h+.04,fy+.9+z*.35);const gold=new THREE.MeshStandardMaterial({color:0xffd068,metalness:.7,roughness:.22});bar(new THREE.Vector3(-5.8,h,fy),new THREE.Vector3(-5.8,h+2.4,fy),.12,gold);bar(new THREE.Vector3(5.8,h,fy),new THREE.Vector3(5.8,h+2.4,fy),.12,gold);box(11.8,.27,.28,gold,0,h+2.4,fy);cameraFocus.set(players[0].x,.8,players[0].y-.45)}
function init3D(){renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,matchMedia("(pointer:coarse)").matches?1.5:2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;scene=new THREE.Scene();scene.background=new THREE.Color(0x7dc5fa);scene.fog=new THREE.Fog(0x7dc5fa,38,85);camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,150);scene.add(new THREE.HemisphereLight(0xe9f8ff,0x69778d,2.1));sun=new THREE.DirectionalLight(0xfff1dd,3.4);sun.position.set(-8,18,10);sun.castShadow=true;sun.shadow.mapSize.set(matchMedia("(pointer:coarse)").matches?1024:2048,matchMedia("(pointer:coarse)").matches?1024:2048);Object.assign(sun.shadow.camera,{left:-22,right:22,top:22,bottom:-22,near:.5,far:65});sun.shadow.bias=-.0003;sun.shadow.normalBias=.025;scene.add(sun,sun.target);const fill=new THREE.DirectionalLight(0xc2e3ff,1.1);fill.position.set(10,6,-12);scene.add(fill);runnerModels=colors.map(runner);resize()}
function resize(){if(!renderer)return;view.w=innerWidth;view.h=innerHeight;renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}
function project(x,y,z=0){const v=new THREE.Vector3(x,z,y).project(camera);return{x:(v.x+1)*innerWidth/2,y:(1-v.y)*innerHeight/2}}
function groundPoint(sx,sy){raycaster.setFromCamera(new THREE.Vector2(sx/innerWidth*2-1,1-sy/innerHeight*2),camera);const v=new THREE.Vector3();if(!raycaster.ray.intersectPlane(floorPlane,v))return null;return{x:clamp(v.x,-5.7,5.7),y:clamp(v.z,.15,6.9)}}
function render(t){if(!renderer||!players.length)return;const dt=Math.min(.05,Math.max(.001,t-lastRenderTime));lastRenderTime=t;const p=players[0],height=p.y<0?Math.min(laneOwner(p).built,-p.y/.65)*.18:0;cameraFocus.set(p.x,height+.8,p.y-.45);const dist=cameraDistance*(innerWidth<650?1.2:1);camera.position.copy(cameraFocus).add(new THREE.Vector3(Math.sin(cameraYaw)*dist,dist*.36,Math.cos(cameraYaw)*dist));camera.lookAt(cameraFocus);sun.position.copy(cameraFocus).add(new THREE.Vector3(-8,18,10));sun.target.position.copy(cameraFocus);
for(const r of players){const m=runnerModels[r.id],h=r.y<0?Math.min(laneOwner(r).built,-r.y/.65)*.18:0,radius=Math.max(.025,Math.sqrt(r.energy/36)*1.23);m.group.position.set(r.x,h,r.y);const turn=Math.atan2(r.dirX,r.dirY);m.body.rotation.y=turn;const moving=state==='playing'&&Math.abs(r.roll-m.last.x)>.0001;m.last.x=r.roll;const swing=moving?Math.sin(r.phase)*.65:0;m.limbs[0].rotation.x=swing;m.limbs[1].rotation.x=-swing;m.body.position.y=moving?Math.abs(Math.sin(r.phase))* .025:0;const reach=radius+.47;m.ball.position.set(r.x+r.dirX*reach,h+radius,r.y+r.dirY*reach);m.ball.visible=r.energy>.001;m.ball.scale.setScalar(radius);const axis=new THREE.Vector3(r.dirY,0,-r.dirX).normalize();m.ball.quaternion.setFromAxisAngle(axis,r.roll);for(let n=0;n<stairModels[r.id].length;n++)stairModels[r.id][n].visible=n<r.built;}renderer.render(scene,camera)}
canvas.addEventListener('contextmenu',e=>e.preventDefault());
function loop(ms){let dt=Math.min((ms-last)/1000,.04);last=ms;if(state==='countdown'){count-=dt;$('countdown').textContent=count>0?Math.ceil(count):T('ready');if(count<-.6){state='playing';$('countdown').textContent='';toastTime=0;$('notice').style.opacity=0;}}if(state==='playing'){elapsed+=dt;for(const p of players){if(state!=='playing')break;updatePlayer(p,dt)}for(const e of effects)e.life-=dt;effects=effects.filter(e=>e.life>0);hud()}if(toastTime>0){toastTime-=dt;if(toastTime<=0)$('notice').style.opacity=0}render(ms/1000);requestAnimationFrame(loop)}
$('start').onclick=()=>{if(state==='loading')return;if(startMode==='resume'){togglePause();return}if(startMode==='next')round=round===3?1:round+1;startRace()};$('restart').onclick=startRace;$('pause').onclick=togglePause;
window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();if(e.key==='Escape'||e.key.toLowerCase()==='p'){if(!e.repeat)togglePause();return}if(state!=='playing')return;keys[e.key.length===1?e.key.toLowerCase():e.key]=true});window.addEventListener('keyup',e=>keys[e.key.length===1?e.key.toLowerCase():e.key]=false);window.addEventListener('blur',()=>{keys={};if(state==='playing')togglePause()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='playing')togglePause()});
let dragControl=null;
canvas.addEventListener('pointerdown',e=>{if(e.button!==0||state!=='playing'||!['gather','stairs'].includes(players[0].mode))return;if(e.pointerType==='mouse'){target=groundPoint(e.clientX,e.clientY);return}if(dragControl)return;e.preventDefault();target=null;dragControl={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId)});
canvas.addEventListener('pointermove',e=>{if(!dragControl||e.pointerId!==dragControl.id)return;e.preventDefault();const dx=e.clientX-dragControl.x,dy=e.clientY-dragControl.y,d=Math.hypot(dx,dy);joystick=d<6?{x:0,y:0}:{x:dx/Math.max(45,d),y:dy/Math.max(45,d)}});
for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,e=>{if(dragControl&&e.pointerId===dragControl.id){dragControl=null;joystick={x:0,y:0};target=null}});
let stickPointer=null;function updateStick(e){const r=$('joystick').getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,m=Math.hypot(dx,dy),radius=r.width*.32;joystick={x:dx/Math.max(m,radius),y:dy/Math.max(m,radius)};$('knob').style.transform=`translate(${joystick.x*radius}px,${joystick.y*radius}px)`}
$('joystick').addEventListener('pointerdown',e=>{if(state!=='playing')return;e.preventDefault();target=null;stickPointer=e.pointerId;$('joystick').setPointerCapture(e.pointerId);updateStick(e)});$('joystick').addEventListener('pointermove',e=>{if(e.pointerId===stickPointer)updateStick(e)});for(const ev of ['pointerup','pointercancel','lostpointercapture'])$('joystick').addEventListener(ev,()=>{stickPointer=null;joystick={x:0,y:0};$('knob').style.transform=''});window.addEventListener('resize',resize);if(window.visualViewport)window.visualViewport.addEventListener('resize',resize);
function boot(){applyLanguage();try{init3D();startRace();applyLanguage();requestAnimationFrame(loop)}catch(e){$('overlay').classList.remove('hidden');$('cardTitle').textContent='Unable to load 3D game';$('description').textContent=String(e);console.error(e)}}boot();
